### ISSUE TITLE
ADU ECU Master Units

### ISSUE THREAD

**Issue by PawelDK91** [Blumlaut/ac-adu-dash#1]
Is there a way that I can change the km/h units to MPH? I love your ECU but its in km/h.

**Comment by Blumlaut** [comment]
you would need to edit the ADU Textures and make some minor code changes to support MPH

**Comment by PawelDK91** [comment]
Do you know how to change the code? 

Sent from Yahoo Mail on Android 
 
  On Fri, Jun 30, 2023 at 3:55 AM, ***@***.***> wrote:   


you would need to edit the ADU Textures and make some minor code changes to support MPH

**Comment by PawelDK91** [comment]
I did change textures but I do not know how to code. Would it be possible to you to provide me with the "minor code changes"?
