### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by hjorthennmods** [Blumlaut/ac-adu-dash#3]
I am having an issue with the dash. 
When i get it into the car, ive downloaded it over again and same problem. 

When i go ingame, the dashboard works, BUT it is blinking, or flashing or whatever. 
And that will not make a very professional looking cara, when its doing that XD 
(not saying the dash is not profesionally made)

How can i fix this?

**Comment by Blumlaut** [comment]
Which dash are you using, which simulator? Does it only happen on a third party device or also if you open the dash in simhub itself?

**Comment by hjorthennmods** [comment]
The ADU5

  *
its used in assetto corsa.

I can see that it works for somebody, but doesnt for me and a friend.
No idea, i dont use simhub tbh, i dont know what it is

________________________________

**Comment by Blumlaut** [comment]
yeah ignore the simhub bit, I was thinking about another thing I made.

would probably be good using the csp lua debug app, also the csp version used is important.
